// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------------- //
// spdif_rx_48000 //
// -------------- //

#define spdif_rx_48000_wrap_target 1
#define spdif_rx_48000_wrap 13
#define spdif_rx_48000_pio_version 0

#define spdif_rx_48000_offset_entry_point 0u

static const uint16_t spdif_rx_48000_program_instructions[] = {
    0x2020, //  0: wait   0 pin, 0                   
            //     .wrap_target
    0x3fa0, //  1: wait   1 pin, 0               [31]
    0xad42, //  2: nop                           [13]
    0x00c6, //  3: jmp    pin, 6                     
    0x40e1, //  4: in     osr, 1                     
    0x0001, //  5: jmp    1                          
    0xbd42, //  6: nop                           [29]
    0x00d0, //  7: jmp    pin, 16                    
    0x4061, //  8: in     null, 1                    
    0x1c0c, //  9: jmp    12                     [28]
    0x3f20, // 10: wait   0 pin, 0               [31]
    0xad42, // 11: nop                           [13]
    0x00ce, // 12: jmp    pin, 14                    
    0x4061, // 13: in     null, 1                    
            //     .wrap
    0x40e1, // 14: in     osr, 1                     
    0x000a, // 15: jmp    10                         
    0x8020, // 16: push   block                      
    0x40e2, // 17: in     osr, 2                     
    0x3f20, // 18: wait   0 pin, 0               [31]
    0xad42, // 19: nop                           [13]
    0x1dd6, // 20: jmp    pin, 22                [29]
    0x000c, // 21: jmp    12                         
    0x40e2, // 22: in     osr, 2                     
    0x0000, // 23: jmp    0                          
};

#if !PICO_NO_HARDWARE
static const struct pio_program spdif_rx_48000_program = {
    .instructions = spdif_rx_48000_program_instructions,
    .length = 24,
    .origin = -1,
    .pio_version = 0,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config spdif_rx_48000_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + spdif_rx_48000_wrap_target, offset + spdif_rx_48000_wrap);
    return c;
}
#endif

