// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------------- //
// spdif_rx_192000 //
// --------------- //

#define spdif_rx_192000_wrap_target 1
#define spdif_rx_192000_wrap 11

#define spdif_rx_192000_offset_entry_point 0u

static const uint16_t spdif_rx_192000_program_instructions[] = {
    0x2020, //  0: wait   0 pin, 0                   
            //     .wrap_target
    0x2ba0, //  1: wait   1 pin, 0               [11]
    0x00c5, //  2: jmp    pin, 5                     
    0x40e1, //  3: in     osr, 1                     
    0x0001, //  4: jmp    1                          
    0xa642, //  5: nop                           [6] 
    0x00ce, //  6: jmp    pin, 14                    
    0x4061, //  7: in     null, 1                    
    0x050a, //  8: jmp    10                     [5] 
    0x2b20, //  9: wait   0 pin, 0               [11]
    0x00cc, // 10: jmp    pin, 12                    
    0x4061, // 11: in     null, 1                    
            //     .wrap
    0x40e1, // 12: in     osr, 1                     
    0x0009, // 13: jmp    9                          
    0x8020, // 14: push   block                      
    0x40e2, // 15: in     osr, 2                     
    0x2b20, // 16: wait   0 pin, 0               [11]
    0x06d3, // 17: jmp    pin, 19                [6] 
    0x000a, // 18: jmp    10                         
    0x40e2, // 19: in     osr, 2                     
    0x0000, // 20: jmp    0                          
};

#if !PICO_NO_HARDWARE
static const struct pio_program spdif_rx_192000_program = {
    .instructions = spdif_rx_192000_program_instructions,
    .length = 21,
    .origin = -1,
};

static inline pio_sm_config spdif_rx_192000_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + spdif_rx_192000_wrap_target, offset + spdif_rx_192000_wrap);
    return c;
}
#endif
